### ISSUE TITLE
feat: 기본 UI 인터페이스 구현

### ISSUE THREAD

**Issue by baxkspace** [baxkspace/fcloud-command#2]
***Description***
---
* 실행파일 초기 진입 시 기본적으로 뜨는 인터페이스 디자인 및 구현

***Todo***
---
- [x] 디자인 구현
- [x] 각 개체 선택 시 selected 되도록 구현
- [x] server 로그인 구현
- [x] client 로그인 구현
- [x] download/upload일 때 back 버튼 기능 구현
- [ ] list next page 구현

***etc***
---
-
