### ISSUE TITLE
fix: download/upload 기능 구현 수정

### ISSUE THREAD

**Issue by baxkspace** [baxkspace/fcloud-command#5]
***Todo***
---
- [x] 파일 업로드 시 mode 문제 해결
- [x] 파일 업로드 시 contents 업로드 안 됨
- [x] download 세그멘테이션 오류

***etc***
---
pull 해서 메인 파일에서 열어 보면서 구현

**Comment by baxkspace** [comment]
아마 mode 잘못 표시되는 건 stat 함수에서 directory가 열리는 건지 path를 잘못 받아 오는 것 같은 느낌임
근데 문제는? 받는 파일마다 다 다르게 뜸 위 문제라면 통일돼서 떠야 하는데
받을 때마다 모드도 다르게 뜸 어디서 오류가 나는지 모르겠음

**Comment by MinhwanO** [comment]
일단 내 컴에서는 다 되긴 함
내가보기에 설정 안해놔서 그런거같음 카톡으로 보낸 거 설정해놓으면 될 거 같음

**Comment by MinhwanO** [comment]
mode 잘못 표시된거는.. stat을 해서 정보를 받아오기 전에 mode = info.st_mode를 해버려서 그럼
순서 바꾸니까 해결!
