### ISSUE TITLE
feat: upload/download 시 예외 처리 구현

### ISSUE THREAD

**Issue by baxkspace** [baxkspace/fcloud-command#6]
***Todo***
---
- [ ] upload - 겹치는 파일 이름 존재 시 예외 처리
- [ ] download - 겹치는 파일 이름 존재 시 예외 처리
- [ ] 예외 처리 후 실패 시 sleep 함수 이용해 screen에 띄우기
- [ ] screen full 상태면 cloud full로 띄우기

***etc***
---
-
